### ISSUE TITLE
The widget didn't work with “$parentIds” equals “0”

### ISSUE THREAD

**Issue by Ronef** [DivanDesign/MODXEvo.plugin.ManagerManager.mm_ddSelectDocuments#1]

**Comment by mediakot** [comment]
Чтобы исправить это нужно в файле ddselectdocuments.php  заменить

`function mm_ddSelectDocuments($tvs = '', $roles = '', $templates = '', $parentIds, $depth = 1, $filter = '', $max = 0, $labelMask = '[+title+] ([+id+])',$allowDoubling = 'true'){
    if (empty($parentIds) || !useThisRule($roles, $templates)){return;}`
на 
`function mm_ddSelectDocuments($tvs = '', $roles = '', $templates = '', $parentIds=0, $depth = 1, $filter = '', $max = 0, $labelMask = '[+title+] ([+id+])',$allowDoubling = 'true'){
    if (!useThisRule($roles, $templates)){return;}`

**Comment by Ronef** [comment]
@mediakot Исправлено.
