### ISSUE TITLE
Не работает если выставить depth больше единицы 

### ISSUE THREAD

**Issue by tanzirev** [DivanDesign/MODXEvo.plugin.ManagerManager.mm_ddSelectDocuments#4]
ManagerManager ver. 0.6.2 
mm_ddSelectDocumentsPlugin ver. 1.2.2

**Comment by tanzirev** [comment]
Разобрался.
параметр max - обязателен. (Даже если 0).

**Comment by Ronef** [comment]
Расскажите пожалуйста подробней, ибо в коде прописано значение по умолчанию для параметра `$max`, следовательно, он не обязателен.

**Comment by tanzirev** [comment]
Если написать вот такой вызов:

`mm_ddSelectDocuments('cat_refer_product', '', '8', '181', '2', 'template=7&published=1&isfolder=0', '0', '[+title+]  ([+id+])');`

то будет работать

А если вот такой:

`mm_ddSelectDocuments('cat_refer_product', '', '8', '181', '2', 'template=7&published=1&isfolder=0', '', '[+title+] ([+id+])');`

то не робит.

Ошибку выдает на 107-ой строке, в файле ddselectdocuments.php

**Comment by Ronef** [comment]
@tanzirev Пофиксили)
