### ISSUE TITLE
ddselectdocuments.php не выдает в jquery плагин параметр allowDoubling

### ISSUE THREAD

**Issue by sashabeep** [DivanDesign/MODXEvo.plugin.ManagerManager.mm_ddSelectDocuments#5]
Версия ddselectdocuments.php 1.2.2
JSON, передаваемый в плагин получается неполным

``` javascript
.............,"value":"39"},{"label":"Сауна (45)","value":"45"}], max: 0, allowDoubling: });
```

то есть после **allowDoubling:** ничего
ddselectdocuments.php строка 137

``` php
'
$j("#tv'.$tv['id'].'").ddMultipleInput({source: '.$jsonDocs.', max: '.$max.', allowDoubling: '.$allowDoubling.'});
';
```

После изменения на

``` php
'
$j("#tv'.$tv['id'].'").ddMultipleInput({source: '.$jsonDocs.', max: '.$max.', allowDoubling: 0});
';
```

работает

**Comment by sashabeep** [comment]
Вызов виджета был такой 

```
mm_ddSelectDocuments('spisokTV', '', '', '6,7', '5', '', 0, '[+title+] ([+id+])');
```

**Comment by Ronef** [comment]
Такого кода в виджете [нет](https://github.com/DivanDesign/MODXEvo.plugin.ManagerManager.mm_ddSelectDocuments/blob/master/ddselectdocuments/ddselectdocuments.php), наверное это неоригинальная версия.

**Comment by sashabeep** [comment]
Я так понимаю, pull request с этим параметром висит давно, неизвестно, зачем он нужен в официальной версии

**Comment by Ronef** [comment]
@sashabeep Повторюсь здесь на всякий случай: В оф. версию MODX накодили без нашего ведома. А мы теперь разгребаем(

**Comment by Ronef** [comment]
Исправлено с версии [1.3](https://github.com/DivanDesign/MODXEvo.plugin.ManagerManager.mm_ddSelectDocuments/releases/tag/v1.3).
